### ISSUE TITLE
[추천 병원 전체] 위치 필터링, 증상 필터링, 병원 리스트

### ISSUE THREAD

**Issue by wonhyuna** [Solution-Challenge-Team/CoDI-FE#19]
## 🔥 Issue
추천 병원 전체 페이지

## ✅ TODO
- [x] 위치 필터링 드롭박스
- [x] 증상 필터링 드롭박스
- [x] 병원 리스트 배치
- [x] 병원 사진
- [x] 병원 이름
- [x] 병원 주소
- [x] 별점
